languaje: node_js
nodejs: 12.13.0

addons:
  sonarcloud:
    organization: "crisan97"
    token:
      secure: 957feacab95ee2314b953ec3b1194b05bdf24567 # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner 